using CryptoExchange.Net.Objects;
using HyperLiquid.Net.Objects.Internal;
using HyperLiquid.Net.Objects.Models;
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace HyperLiquid.Net.Converters
{

    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidOpenOrderUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidPositionUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidAllDexPositionUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidBalanceUpdate>))]

    [JsonSerializable(typeof(HyperLiquidRequest))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<Dictionary<string, decimal>>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidKline[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidOrderBook>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidFeeInfo>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidDefault>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidAccountLedger>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidRateLimit>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<int>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidSubAccount[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidUserRole>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidUserAgent[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidStakingDelegation[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidStakingSummary>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidStakingHistory[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidStakingReward[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponseAuth<HyperLiquidTwapCancelResult>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponseAuth<HyperLiquidTwapOrderResult>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponseAuth<HyperLiquidOrderResultIntWrapper>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidResponse>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidOrderStatus[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponseAuth<object>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponseAuth<HyperLiquidOrderStatus[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponseAuth<HyperLiquidCancelResult>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidOrderStatusResult>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidUserTrade[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidOrder[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidOpenOrder[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<bool>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidFuturesUserSymbolUpdate>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidUserLedger<HyperLiquidUserFunding>[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidFuturesAccount>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidPerpDex[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidFuturesExchangeInfo[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidFuturesExchangeInfo>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidFuturesExchangeInfoAndTickers>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidFundingRate[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<string[]>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidPerpDexLimit>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidPerpDexStatus>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidBalances>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidAssetInfo>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidExchangeInfoAndTickers>>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSocketResponse<HyperLiquidSpotExchangeInfo>>))]

    [JsonSerializable(typeof(HyperLiquidUserAgent[]))]
    [JsonSerializable(typeof(object[]))]
    [JsonSerializable(typeof(Dictionary<string, decimal>))]
    [JsonSerializable(typeof(List<ParameterCollection>))]
    [JsonSerializable(typeof(HyperLiquidResponse<HyperLiquidOrderResultIntWrapper>))]
    [JsonSerializable(typeof(HyperLiquidResponse<HyperLiquidCancelResult>))]
    [JsonSerializable(typeof(HyperLiquidResponse<HyperLiquidTwapOrderResultIntWrapper>))]
    [JsonSerializable(typeof(HyperLiquidResponse<HyperLiquidTwapCancelResult>))]
    [JsonSerializable(typeof(CancelResultConverter.ErrorMessage))]
    [JsonSerializable(typeof(HyperLiquidResponse<HyperLiquidDefault>))]
    [JsonSerializable(typeof(HyperLiquidMarginTableEntry))]
    [JsonSerializable(typeof(HyperLiquidSubAccount[]))]
    [JsonSerializable(typeof(HyperLiquidUserRole))]
    [JsonSerializable(typeof(HyperLiquidResponse))]
    [JsonSerializable(typeof(HyperLiquidPerpDex[]))]
    [JsonSerializable(typeof(HyperLiquidPerpDexLimit))]
    [JsonSerializable(typeof(HyperLiquidPerpDexStatus))]

    [JsonSerializable(typeof(HyperLiquidStakingHistory[]))]
    [JsonSerializable(typeof(HyperLiquidStakingSummary))]
    [JsonSerializable(typeof(HyperLiquidStakingDelegation[]))]
    [JsonSerializable(typeof(HyperLiquidStakingReward[]))]

    // End manual defined attributes

    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidBookTicker>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<string>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidUserEventUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidTrade[]>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidOrderStatus[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidUserFunding>[]))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidDeposit[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidWithdrawal[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidInternalTransfer[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidLiquidation[]>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidSpotTransfer[]>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidSubscribeRequest>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidMidsUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidKline>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidOrderBook>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidLedgerUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidUserUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidWebDataV3Update>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidUserTradeUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidTwapTradeUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidTwapOrderUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidFuturesTickerUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidFuturesUserSymbolUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidUserFundingUpdate>))]
    [JsonSerializable(typeof(HyperLiquidSocketUpdate<HyperLiquidTickerUpdate>))]
    [JsonSerializable(typeof(IDictionary<string, object>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidDeposit>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidWithdrawal>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidInternalTransfer>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidLiquidation>))]
    [JsonSerializable(typeof(HyperLiquidUserLedger<HyperLiquidSpotTransfer>))]
    [JsonSerializable(typeof(HyperLiquidUserTrade[]))]
    [JsonSerializable(typeof(HyperLiquidTwapStatus[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderStatus[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderUpdate[]))]
    [JsonSerializable(typeof(HyperLiquidTwapTradeUpdate[]))]
    [JsonSerializable(typeof(HyperLiquidAccountLedger[]))]
    [JsonSerializable(typeof(HyperLiquidLiquidationPosition[]))]
    [JsonSerializable(typeof(HyperLiquidAssetInfo[]))]
    [JsonSerializable(typeof(HyperLiquidAssetGenesis[]))]
    [JsonSerializable(typeof(AddressBalance[]))]
    [JsonSerializable(typeof(AddressIndexBalance[]))]
    [JsonSerializable(typeof(HyperLiquidBalances[]))]
    [JsonSerializable(typeof(HyperLiquidBalance[]))]
    [JsonSerializable(typeof(HyperLiquidCancelRequest[]))]
    [JsonSerializable(typeof(HyperLiquidCancelByClientOrderIdRequest[]))]
    [JsonSerializable(typeof(HyperLiquidCancelResult[]))]
    [JsonSerializable(typeof(HyperLiquidEditOrderRequest[]))]
    [JsonSerializable(typeof(HyperLiquidExchangeInfoAndTickers[]))]
    [JsonSerializable(typeof(HyperLiquidTicker[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfo[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfoVolume[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfoSchedule[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfoFeeTier[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfoFeeTierRate[]))]
    [JsonSerializable(typeof(HyperLiquidFeeInfoFeeTierRateMarketMaker[]))]
    [JsonSerializable(typeof(HyperLiquidFundingRate[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesAccount[]))]
    [JsonSerializable(typeof(HyperLiquidMarginSummary[]))]
    [JsonSerializable(typeof(HyperLiquidPosition[]))]
    [JsonSerializable(typeof(HyperLiquidPositionInfo[]))]
    [JsonSerializable(typeof(HyperLiquidPositionLeverage[]))]
    [JsonSerializable(typeof(HyperLiquidPositionFunding[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesExchangeInfo[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesSymbol[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesExchangeInfoAndTickers[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesTicker[]))]
    [JsonSerializable(typeof(HyperLiquidFuturesUserSymbolUpdate))]
    [JsonSerializable(typeof(HyperLiquidFuturesUserSymbolUpdate[]))]
    [JsonSerializable(typeof(HyperLiquidLeverage[]))]
    [JsonSerializable(typeof(HyperLiquidKline[]))]
    [JsonSerializable(typeof(HyperLiquidOpenOrder[]))]
    [JsonSerializable(typeof(HyperLiquidOrder[]))]
    [JsonSerializable(typeof(HyperLiquidOrderBook[]))]
    [JsonSerializable(typeof(HyperLiquidOrderBookLevels[]))]
    [JsonSerializable(typeof(HyperLiquidOrderBookEntry[]))]
    [JsonSerializable(typeof(HyperLiquidOrderRequest[]))]
    [JsonSerializable(typeof(HyperLiquidOrderResultIntWrapper[]))]
    [JsonSerializable(typeof(HyperLiquidOrderResultInt[]))]
    [JsonSerializable(typeof(HyperLiquidOrderResult[]))]
    [JsonSerializable(typeof(HyperLiquidOrderStatusResult[]))]
    [JsonSerializable(typeof(HyperLiquidRateLimit[]))]
    [JsonSerializable(typeof(HyperLiquidSpotExchangeInfo[]))]
    [JsonSerializable(typeof(HyperLiquidSymbol[]))]
    [JsonSerializable(typeof(HyperLiquidAsset[]))]
    [JsonSerializable(typeof(HyperLiquidSymbolReference[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderResultIntWrapper[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderResultInt[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderResult[]))]
    [JsonSerializable(typeof(HyperLiquidTwapOrderStatusDesc[]))]
    [JsonSerializable(typeof(HyperLiquidUserUpdate[]))]
    [JsonSerializable(typeof(HyperLiquidPong))]
    [JsonSerializable(typeof(HyperLiquidPing))]
    [JsonSerializable(typeof(HyperLiquidUnsubscribeRequest))]
    [JsonSerializable(typeof(HyperLiquidSocketRequest))]
    [JsonSerializable(typeof(string))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(long?))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(decimal?))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(DateTime))]
    [JsonSerializable(typeof(DateTime?))]
    internal partial class HyperLiquidSourceGenerationContext : JsonSerializerContext
    {
    }
}
